name: AWS FreeRTOS CI

on:
  push:

jobs:
  build:
    name: Build cypress/CY8CKIT_064S0S2_4343W
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1
    - name: Install gnuarmemb
      run: |
        mkdir -p ~/bin
        mkdir -p ~/opt
        wget -q https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/RC2.1/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
        tar -xaf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 -C ~/opt/
        #echo "::add-path::~/bin:~/opt/gcc-arm-none-eabi-9-2019-q4-major/bin"
        echo "::add-path::~/opt/gcc-arm-none-eabi-9-2019-q4-major/bin"
    - name: Check gnuarmemb version
      run: |
        echo $PATH
        arm-none-eabi-gcc --version
